name: torch-ngp
channels:
  - pytorch
  - conda-forge
dependencies:
  - python
  - cudatoolkit=11.3
  - ninja
  - trimesh
  - opencv
  - tensorboardX
  - pytorch==1.11.0
  - numpy 
  - pandas
  - tqdm
  - matplotlib
  - rich
  - packaging
  - scipy
  - pip
  - pip:
    - imageio
    - lpips
    - torch-ema
    - PyMCubes
    - pysdf
    - dearpygui
